name = "zenlock"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables will be read from Cloudflare Dashboard / Wrangler secrets
